alias vim="nvim"
alias ls="eza --long --header --git --all --icons=always"
alias ll="eza -l -h --icons=always"
alias cat="bat"
# alias curl="curlie"
alias grep="rg"
# alias man="tldr"
alias wget='wget --hsts-file="$XDG_DATA_HOME/wget-hsts"'
alias weather="curl v2.wttr.in/Guwahati"
alias cd="z"
alias glp="git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset'"
