github.com:
    users:
        abhigyanmadhukalya:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: abhigyanmadhukalya
